###
//Create a user
GET  http://localhost:5022/loginpage
Content-Type: application/json

{
    
    "email": "testing@gmail.com",
    "password": "testing" 
  
}

###

GET url HTTP/1.1   http://localhost:5022/barangprediksilatest
Content-Type: application/json

{  
    
}

###

GET    http://localhost:5022/barangkeluarweek
Content-Type: application/json

